---
title: "Developing Data Products - Week 3 Assignment"
author: "dortje"
date: "18 November 2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Plot of mtcars
Plotting variables hp (x axis), mpg(y axis) and cyl (color) including a regression line for lm(mpg~hp).

```{r plot_cars, warnings=FALSE, message=FALSE}
library(plotly)
data(mtcars)
mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$vs <- as.factor(mtcars$vs)
mtcars$am <- as.factor(mtcars$am)

fit <- lm(mpg ~ hp, data=mtcars)

mtcars %>%
    plot_ly(x=~hp) %>%
    add_markers(y=~mpg, color=~cyl, mode="markers", 
        text=~paste(rownames(mtcars))) %>%
    add_lines(x=~hp, y=fitted(fit), name="lm")
```

## Code for the Plot

```{r code_plot, echo = TRUE, eval=FALSE}
library(plotly)
data(mtcars)
mtcars$cyl <- as.factor(mtcars$cyl)
mtcars$vs <- as.factor(mtcars$vs)
mtcars$am <- as.factor(mtcars$am)

fit <- lm(mpg ~ hp, data=mtcars)

mtcars %>%
    plot_ly(x=~hp) %>%
    add_markers(y=~mpg, color=~cyl, mode="markers", 
        text=~paste(rownames(mtcars))) %>%
    add_lines(x=~hp, y=fitted(fit), name="lm")
```

## Thank you
- Danke
- Gracias
- Merci
- Dank u
- Tack